/*
 * Copyright (c) 2018-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

/* Note - For packaging reasons, do not move this file from src/include/non_abi */

#pragma once

// clang-format off

#define NVSHMEM_VENDOR_MAJOR_VERSION 3
#define NVSHMEM_VENDOR_MINOR_VERSION 7
#define NVSHMEM_VENDOR_PATCH_VERSION 1
#define NVSHMEM_VENDOR_PACKAGE_VERSION 0
#define NVSHMEM_VENDOR_BASE_VERSION_STRING "3.7.1"
#define NVSHMEM_VENDOR_NUMERIC_VERSION_STRING "3.7.1.0"
#define NVSHMEM_VENDOR_ARTIFACT_VERSION_STRING "3.7.1"
#define NVSHMEM_VENDOR_PACKAGE_VERSION_STRING "3.7.1"
#define NVSHMEM_VENDOR_PACKAGE_RELEASE_STRING "0"
#define NVSHMEM_VENDOR_RPM_PACKAGE_VERSION_STRING "3.7.1"
#define NVSHMEM_VENDOR_RPM_PACKAGE_RELEASE_STRING "0"
#define NVSHMEM_VENDOR_VERSION_STAGE "release"
#define NVSHMEM_VENDOR_VERSION_STAGE_NUMBER ""
#define NVSHMEM_TRANSPORT_PLUGIN_MAJOR_VERSION 6
#define NVSHMEM_TRANSPORT_PLUGIN_MINOR_VERSION 0
#define NVSHMEM_TRANSPORT_PLUGIN_PATCH_VERSION 0
#define NVSHMEM_BOOTSTRAP_PLUGIN_MAJOR_VERSION 3
#define NVSHMEM_BOOTSTRAP_PLUGIN_MINOR_VERSION 0
#define NVSHMEM_BOOTSTRAP_PLUGIN_PATCH_VERSION 0
#define NVSHMEM_BUILD_VARS "NVSHMEM_ARTIFACT_VERSION=3.7.1 NVSHMEM_DEBUG=OFF NVSHMEM_DEVEL=OFF NVSHMEM_DEFAULT_PMI2=OFF NVSHMEM_DEFAULT_PMIX=OFF NVSHMEM_DEFAULT_UCX=OFF NVSHMEM_ENABLE_ALL_DEVICE_INLINING=OFF NVSHMEM_BUILD_P2P_ONLY=OFF NVSHMEM_GPU_COLL_USE_LDST=OFF NVSHMEM_IBGDA_SUPPORT=ON NVSHMEM_IBGDA_SUPPORT_GPUMEM_ONLY=OFF NVSHMEM_GPUNETIO_SUPPORT=ON NVSHMEM_IBDEVX_SUPPORT=ON NVSHMEM_IBRC_SUPPORT=ON NVSHMEM_LIBFABRIC_SUPPORT=ON NVSHMEM_MPI_SUPPORT=ON NVSHMEM_NVTX=ON NVSHMEM_PMIX_SUPPORT=ON NVSHMEM_SHMEM_SUPPORT=ON NVSHMEM_TEST_STATIC_LIB=OFF NVSHMEM_TIMEOUT_DEVICE_POLLING=OFF NVSHMEM_TRACE=OFF NVSHMEM_UCX_SUPPORT=ON NVSHMEM_USE_DLMALLOC=OFF NVSHMEM_USE_NCCL=ON NVSHMEM_USE_GDRCOPY=ON NVSHMEM_USE_MLX5DV=ON NVSHMEM_ENABLE_CFT_HANDLES=OFF NVSHMEM_PRIORITIZE_LOGICAL_ENDPOINT=OFF NVSHMEM_VERBOSE=OFF CUDA_HOME=/dvs/p4/build/sw/rel/gpgpu/toolkit/r13.2/build/cuda GDRCOPY_HOME=/dvs/p4/build/sw/rel/gpgpu/toolkit/r13.2/gdrcopy_build LIBFABRIC_HOME=/data/tmp/libfabric_install MPI_HOME=/data/tmp/openmpi_install NCCL_HOME=/dvs/p4/build/sw/rel/gpgpu/toolkit/r13.2/nccl/build NVSHMEM_PREFIX=/dvs/p4/build/sw/rel/gpgpu/toolkit/r13.2/main_nvshmem/install PMIX_HOME=/data/tmp/pmix_install SHMEM_HOME=/data/tmp/openmpi_install CUTLASS_HOME= UCX_HOME=/dvs/p4/build/sw/gpgpu/openucx/build"

// clang-format on
